project_id = "ahcttlbvgjbdzhholyei"

[functions.chatbot-ai]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.generate-automation]
verify_jwt = true

[functions.help-ai]
verify_jwt = true

[functions.auto-setup]
verify_jwt = true

[functions.ai-auto-tune]
verify_jwt = true

[functions.ai-create-negocio]
verify_jwt = true

[functions.ai-create-chatbot]
verify_jwt = true

[functions.ai-analyze-opportunities]
verify_jwt = true