-- Habilitar REPLICA IDENTITY FULL para realtime em todas as tabelas
ALTER TABLE chatbots REPLICA IDENTITY FULL;
ALTER TABLE automacoes REPLICA IDENTITY FULL;
ALTER TABLE negocios REPLICA IDENTITY FULL;
ALTER TABLE leads REPLICA IDENTITY FULL;
ALTER TABLE vendas REPLICA IDENTITY FULL;
ALTER TABLE agendamentos REPLICA IDENTITY FULL;