// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyezhhnwikxjigqdydce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZXpoaG53aWt4amlncWR5ZGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDk3MTYsImV4cCI6MjA3MzA4NTcxNn0.Us_1ZZLbD-WONdhz6X72NMY21mRYXgko1ClDYWD4VvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});